Add space command

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -9,12 +9,12 @@ __compose_exe="docker compose"
 __compose_upgraded=0
 
 
-dodocker() {
+__dodocker() {
     $__docker_exe "$@"
 }
 
 
-docompose() {
+__docompose() {
     $__compose_exe "$@"
 }
 
@@ -205,9 +205,9 @@ install() {
     done
     if [[ "$__distro" = "ubuntu" ]]; then
         __major_version=$(lsb_release -r | cut -d: -f2 | sed s/'^\t'// | cut -d. -f1)
-        if [ "${__major_version}" -lt 20 ]; then
+        if [ "${__major_version}" -lt 22 ]; then
             echo "${__project_name} cannot install Docker on Ubuntu ${__major_version}."
-            echo "Consider upgrading to 20.04 and then 22.04."
+            echo "Consider upgrading to 22.04 and then 24.04."
             exit 1
         fi
         if [ -z "$(which docker)" ]; then
@@ -238,9 +238,9 @@ install() {
             ${__auto_sudo} apt-get update
             ${__auto_sudo} apt-get -y install ca-certificates curl gnupg lsb-release chrony pkg-config
             __major_version=$(lsb_release -r | cut -f2)
-            if [ "${__major_version}" -lt 10 ]; then
+            if [ "${__major_version}" -lt 11 ]; then
                 echo "${__project_name} cannot install Docker on Debian ${__major_version}."
-                echo "Consider upgrading to 10, then 11 and then 12."
+                echo "Consider upgrading to 11 and then 12."
                 exit 1
             fi
             ${__auto_sudo} mkdir -p /etc/apt/keyrings
@@ -271,61 +271,113 @@ install() {
 }
 
 
-# Warn user if space is low, so they can prune
-check_disk_space() {
-    __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
+__get_docker_free_space() { # set __free_space to what's available to Docker
+  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
+    __free_space=$(__dodocker run --rm -v macos-space-check:/dummy busybox df -P /dummy | awk '/[0-9]%/{print $(NF-2)}')
+  else
+    __docker_dir=$(__dodocker system info --format '{{.DockerRootDir}}')
     __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
+  fi
 
-    re='^[0-9]+$'
-    if ! [[ "${__free_space}" =~ $re ]] ; then
-        echo "Unable to determine free disk space. This is likely a bug."
-        echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
-        exit 70
+  __regex='^[0-9]+$'
+  if ! [[ "${__free_space}" =~ $__regex ]] ; then
+    echo "Unable to determine free disk space. This is likely a bug."
+    if [[ "$OSTYPE" == "darwin"* ]]; then
+      echo "df reports $(__dodocker run --rm -v macos-space-check:/dummy busybox df -P /dummy) and __free_space is ${__free_space}"
+    else
+      echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
     fi
-
-    var="COMPOSE_FILE"
-    value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" ".env" || true)
-
-# Literal match intended
-# shellcheck disable=SC2076
-    if [[ "${value}" =~ "opera.yml" ]] && [[ "${__free_space}" -lt 104857600 ]]; then
-        echo ""
-        echo "You are running Fantom Opera and have less than 100 GiB of free disk space."
-        echo "If Avail reads 40 GiB or more, prune with ./ethd prune-opera:"
-        echo ""
-        df -h "${__docker_dir}"
-        echo ""
-        echo "If it's less than 40 GiB, you may need to resync Opera from scratch."
-        echo ""
-    elif [[ "${__free_space}" -lt 52428800 ]]; then
-        echo ""
-        echo "You have less than 50 GiB of free disk space:"
-        echo ""
-        df -h "${__docker_dir}"
-        echo ""
-        echo "Pruning does not appear an option for your client mix."
-        echo "A resync may help."
-        echo "If total space is less than 1.5 TiB, consider cloning to a larger drive."
-        echo ""
-    fi
+    exit 70
+  fi
 }
 
 
-nag_os_version() {
+__display_docker_dir() {
+  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
+    echo "Here's total and used space on Docker's virtual volume"
+    __dodocker run --rm -v macos-space-check:/dummy busybox df -h /dummy
+  else
+    echo "Here's total and used space on ${__docker_dir}"
+    df -h "${__docker_dir}"
+  fi
+}
+
+
+__display_docker_volumes() {
+  echo
+  if [ -z "$(__dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_[^_]+")" ]; then
+    echo "There are no Docker volumes for this copy of ${__project_name}"
+    echo
+  else
+    echo "Here are the Docker volumes used by this copy of ${__project_name} and their space usage:"
+    __dodocker system df -v | grep -A 50 "VOLUME NAME" | grep "^$(basename "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"
+    echo
+  fi
+  echo "If there is some mystery space being taken up, try \"sudo ncdu /\"."
+  echo
+}
+
+
+space() {
+  __get_docker_free_space
+  echo
+  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
+    echo "You have $(( __free_space / 1024 / 1024 )) GiB free for Docker volumes"
+  else
+    echo "You have $(( __free_space / 1024 / 1024 )) GiB free on ${__docker_dir}"
+  fi
+  echo
+  __display_docker_dir
+  __display_docker_volumes
+}
+
+
+# Warn user if space is low, so they can prune
+__check_disk_space() {
+  __get_docker_free_space
+
+  var="COMPOSE_FILE"
+  value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" ".env" || true)
+
+# Literal match intended
+# shellcheck disable=SC2076
+  if [[ "${value}" =~ "opera.yml" ]] && [[ "${__free_space}" -lt 104857600 ]]; then
+    echo
+    echo "You are running Fantom Opera and have less than 100 GiB of free disk space."
+    echo "If Avail reads 40 GiB or more, prune with ./ethd prune-opera:"
+    echo
+    __display_docker_dir
+    echo
+    echo "If it's less than 40 GiB, you may need to resync Opera from scratch."
+    echo
+  elif [[ "${__free_space}" -lt 52428800 ]]; then
+    echo
+    echo "You have less than 50 GiB of free disk space:"
+    echo
+    __display_docker_dir
+    echo
+    echo "Pruning does not appear an option for your client mix."
+    echo "If total space is less than 1.8 TiB, consider cloning to a larger drive."
+    __display_docker_volumes
+  fi
+}
+
+
+__nag_os_version() {
     if [[ "$__distro" = "ubuntu" ]]; then
       __major_version=$(lsb_release -r | cut -d: -f2 | sed s/'^\t'// | cut -d. -f1)
-      if [ "${__major_version}" -lt 20 ]; then
+      if [ "${__major_version}" -lt 22 ]; then
          echo
-         echo "Ubuntu ${__major_version} is older than the recommended 22.04 or 20.04 version."
+         echo "Ubuntu ${__major_version} is older than the recommended 24.04 or 22.04 version."
          echo
       fi
     fi
 
     if [[ "$__distro" =~ "debian" ]]; then
       __major_version=$(lsb_release -r | cut -f2)
-      if [ "${__major_version}" -lt 10 ]; then
+      if [ "${__major_version}" -lt 11 ]; then
          echo
-         echo "Debian ${__major_version} is older than the recommended 10, 11 or 12 version."
+         echo "Debian ${__major_version} is older than the recommended 11 or 12 version."
          echo
       fi
     fi
@@ -355,7 +407,7 @@ update() {
         exit 1
     fi
 
-    __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
+    __docker_dir=$(__dodocker system info --format '{{.DockerRootDir}}')
     __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
 
     re='^[0-9]+$'
@@ -382,9 +434,9 @@ update() {
 
     envmigrate
 
-    dodocker system prune --force
-    docompose --profile tools pull
-    docompose --profile tools build --pull
+    __dodocker system prune --force
+    __docompose --profile tools pull
+    __docompose --profile tools build --pull
 
     if [ "${__migrated}" -eq 1 ] && ! cmp -s "${ENV_FILE}" "${ENV_FILE}".source; then
         cp "${ENV_FILE}".source "${ENV_FILE}".bak
@@ -404,7 +456,7 @@ find the original contents in ${ENV_FILE}.bak."
 
     echo
     echo "An $__me up command will start using the new images and configuration."
-    nag_os_version
+    __nag_os_version
 
     unset ETHDSECUNDO
     check_for_snap
@@ -474,7 +526,7 @@ upgrade() {
 
 
 start() {
-    docompose up -d --remove-orphans
+    __docompose up -d --remove-orphans
 }
 
 
@@ -489,7 +541,7 @@ run() {
 
 
 stop() {
-    docompose down --remove-orphans "$@"
+    __docompose down --remove-orphans "$@"
 }
 
 
@@ -507,17 +559,17 @@ restart() {
 
 
 logs() {
-    docompose logs "$@"
+    __docompose logs "$@"
 }
 
 
 cmd() {
-    docompose "$@"
+    __docompose "$@"
 }
 
 
 terminate() {
-    if [ -z "$(dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_[^_]+")" ]; then
+    if [ -z "$(__dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_[^_]+")" ]; then
         echo "There are no data stores - Docker volumes - left to remove for this ${__app_name}."
         stop
         exit 0
@@ -534,7 +586,7 @@ terminate() {
     down
 # In this case I want the word splitting, so rm can remove all volumes
 # shellcheck disable=SC2046
-    dodocker volume rm $(dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_[^_]+")
+    __dodocker volume rm $(__dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_[^_]+")
     echo
     echo "All containers stopped and all volumes deleted"
     echo
@@ -588,14 +640,14 @@ version() {
     # Client versions
     case "${value}" in
         *opera.yml* )
-            docompose exec opera opera version
+            __docompose exec opera opera version
             echo
             ;;&
         *grafana.yml* )
-            docompose exec prometheus /bin/prometheus --version
+            __docompose exec prometheus /bin/prometheus --version
             echo
             echo -n "Grafana "
-            docompose exec grafana /run.sh -v
+            __docompose exec grafana /run.sh -v
             echo
             ;;&
     esac
@@ -648,7 +700,7 @@ prune-opera() {
         rpc_port="${BASH_REMATCH[1]}"
     fi
 
-    sync_status=$(docompose exec -T opera wget -qO- "http://localhost:$rpc_port" --header 'Content-Type: application/json' --post-data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}')
+    sync_status=$(__docompose exec -T opera wget -qO- "http://localhost:$rpc_port" --header 'Content-Type: application/json' --post-data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}')
     exitstatus=$?
     if [ $exitstatus -ne 0 ]; then
         echo "Unable to connect to Fantom Opera: Is it running?"
@@ -665,7 +717,7 @@ prune-opera() {
         exit 1
     fi
 
-    node_logs=$(docompose logs --no-color --tail 1000 opera)
+    node_logs=$(__docompose logs --no-color --tail 1000 opera)
     if [[ "${node_logs}" =~ "snapshot generation" && ! "${node_logs}" =~ "Generated state" ]]; then
         echo "Fantom Opera has not finished generating a state snapshot yet, aborting."
         exit 1
@@ -694,8 +746,8 @@ prune-opera() {
     echo ""
     echo "Starting Fantom Opera prune"
     echo ""
-    docompose run --rm set-prune-marker "touch /var/lib/opera/prune-marker"
-    docompose stop opera && docompose rm -f opera
+    __docompose run --rm set-prune-marker "touch /var/lib/opera/prune-marker"
+    __docompose stop opera && __docompose rm -f opera
     start
     echo ""
     echo "Prune is running, you can observe it with './ethd logs -f opera'"
@@ -709,42 +761,44 @@ the \"Compacting database\" stage it may not output logs for an hour or so, that
 
 
 help() {
-    echo "usage: ${__me} [-h|--help] <command>"
-    echo
-    echo "commands:"
-    echo "  install"
-    echo "     attempts to install Docker and Docker Compose for you"
-    echo "  update "
-    echo "     updates all client versions and ${__project_name} itself"
-    echo "  up|start"
-    echo "     starts the ${__app_name}, or restarts containers that had their image or"
-    echo "     configuration changed"
-    echo "  down|stop [service-name]"
-    echo "     stops the ${__app_name}, or a specific service by name"
-    echo "  restart [service-name]"
-    echo "     restarts the ${__app_name}, or a specific service by name, a combination of down and up"
-    echo "  version"
-    echo "     prints the version(s) of currently running client(s)"
-    echo "  logs"
-    echo "     shows logs"
-    echo "  cmd <command>"
-    echo "     executes an arbitrary Docker Compose command. Use \"cmd help\" to list them"
-    echo "  terminate"
-    echo "     stops the ${__app_name} and destroys all data stores"
-    echo "  prune-opera"
-    echo "     stops Opera and offline prunes the database"
-    echo "  help"
-    echo "      print this help screen"
-    echo
-    echo
-    echo "The logs command can be appended by flags and specify the container(s). example: "
-    echo
-    echo "  $__me logs -f --tail 50 ${__sample_service}"
-    echo "    shows logs only for ${__sample_service} service"
-    echo
-    echo
-    echo "$__me will attempt to use sudo as needed for Docker commands"
-    echo
+  echo "usage: ${__me} [-h|--help] <command>"
+  echo
+  echo "commands:"
+  echo "  install"
+  echo "     attempts to install Docker and Docker Compose for you"
+  echo "  update "
+  echo "     updates all client versions and ${__project_name} itself"
+  echo "  up|start"
+  echo "     starts the ${__app_name}, or restarts containers that had their image or"
+  echo "     configuration changed"
+  echo "  down|stop [service-name]"
+  echo "     stops the ${__app_name}, or a specific service by name"
+  echo "  restart [service-name]"
+  echo "     restarts the ${__app_name}, or a specific service by name, a combination of down and up"
+  echo "  version"
+  echo "     prints the version(s) of currently running client(s)"
+  echo "  logs"
+  echo "     shows logs"
+  echo "  cmd <command>"
+  echo "     executes an arbitrary Docker Compose command. Use \"cmd help\" to list them"
+  echo "  terminate"
+  echo "     stops the ${__app_name} and destroys all data stores"
+  echo "  prune-opera"
+  echo "     stops Opera and offline prunes the database"
+  echo "  space"
+  echo "    show Docker volume space usage"
+  echo "  help"
+  echo "      print this help screen"
+  echo
+  echo
+  echo "The logs command can be appended by flags and specify the container(s). example: "
+  echo
+  echo "  $__me logs -f --tail 50 ${__sample_service}"
+  echo "    shows logs only for ${__sample_service} service"
+  echo
+  echo
+  echo "$__me will attempt to use sudo as needed for Docker commands"
+  echo
 }
 
 
@@ -805,18 +859,18 @@ if [ "${__old_compose}" -eq 1 ]; then
   exit 0
 fi
 
-if ! dodocker images >/dev/null 2>&1; then
+if ! __dodocker images >/dev/null 2>&1; then
     echo "Please ensure you can call $__docker_exe before running ${__me}."
     exit 1
 fi
 
-if ! docompose --help >/dev/null 2>&1; then
+if ! __docompose --help >/dev/null 2>&1; then
     echo "Please ensure you can call $__compose_exe before running ${__me}."
     exit 1
 fi
 
 case "$__command" in
-    help|update|up|start|down|stop|restart|version|logs|cmd|terminate|prune-opera)
+    help|update|up|start|down|stop|restart|version|logs|cmd|terminate|prune-opera|space)
         $__command "$@";;
     *)
         echo "Unrecognized command $__command"
@@ -824,7 +878,7 @@ case "$__command" in
         ;;
 esac
 
-check_disk_space
+__check_disk_space
 
 if [ "${__compose_upgraded}" -eq 1 ]; then
   echo
